### ISSUE TITLE
Use try-async instead of current hacky solution

### ISSUE THREAD

**Issue by ArtskydJ** [coding-in-the-wild/just-login-session-state#10]
See this file: https://github.com/coding-in-the-wild/just-login-session-state/blob/master/test/helpers/assertAsyncError.js

My version was hacky. Apparently there is a much better way of writing this. Use [`try-async`](https://github.com/IonicaBizau/try-async) instead of my hacky version.

**Comment by TehShrike** [comment]
It might be reasonable to update everything to a promise-based interface anyway.

If promises are used everywhere internally, and `then-nodeify` is called on any API that just-login exposes, the API will be backwards-compatible.

**Comment by ArtskydJ** [comment]
I like the idea of converting the just-login modules to a promise-based interface. I don't see myself doing it any time soon...

**Comment by ArtskydJ** [comment]
Maybe we can make an issue somewhere (or open one on every just-login module) for converting to a promise-based API.
