### ISSUE TITLE
Session Expiration

### ISSUE THREAD

**Issue by ArtskydJ** [coding-in-the-wild/just-login-session-state#3]
Is session expiration in `just-login-session-state` or `just-login-example-session-manager`?

https://github.com/coding-in-the-wild/just-login-session-state/blob/master/index.js
https://github.com/coding-in-the-wild/just-login-example-session-manager/blob/master/index.js

They both seem to do it...

Or I'm missing something obvious.

**Comment by TehShrike** [comment]
Huh, yeah, the expiration probably shouldn't have been in the example-session-manager at all.  I'm surprised we missed that.

**Comment by ArtskydJ** [comment]
I think we put session expiration into `example-session-manager` because we wanted to get it out of the `core`; I don't think it was pulled out of the `core` until v2.0.0.

I think it makes sense to be in `session-state`.

**Comment by TehShrike** [comment]
Yeah, I checked, it was in the core before 2.0.0.  I agree that it makes sense in session-state.

I think the rest of just-login-example-session-manager makes sense once the expiration stuff is dropped.  And at that point I wonder if we can just make it another optional just-login module, and not keep it named like it's specific to the example?

**Comment by TehShrike** [comment]
See [this new issue on just-login-example-session-manager](https://github.com/coding-in-the-wild/just-login-example-session-manager/issues/3)

**Comment by TehShrike** [comment]
Fixed in https://github.com/coding-in-the-wild/just-login-session-state/pull/5
