### ISSUE TITLE
just-login-core should be considered immutable

### ISSUE THREAD

**Issue by TehShrike** [coding-in-the-wild/just-login-session-state#4]
I feel like this function should not modify the original just-login-core, but should instead return a new just-login-core with the over-written methods, that has the original just-login-core as a prototype.

Thoughts?  I'm a big fan of immutability with mixins like this.

**Comment by ArtskydJ** [comment]
I don't know why someone would want both objects; the original core and the extended core.

Right now it's like levelup:

``` js
var level = require('level-mem')
var sublevel = require('level-sublevel')
var db = level()
sublevel(db)
// now you can do db.sublevel('thing')
```

I tend to support immutability, but I feel like if you're extending the functionality just at startup, I don't mind doing it this way.

Also, I think event emitters in the prototype don't work right.

I could be convinced either way.

**Comment by TehShrike** [comment]
I think level-sublevel is actually incorrect in its implementation - rvagg's [level-spaces](https://www.npmjs.com/package/level-spaces) doesn't modify the original levelup db at all.

I know I've made objects in the past that prototypically inherited event emitters, I can't remember any gotchas (though they may exist).
